apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: libraryapi-nginx:latest
        ports:
        - containerPort: 443
        - containerPort: 80
        - containerPort: 81
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - name: https
      protocol: TCP
      port: 4433
      targetPort: 443
    - name: http
      protocol: TCP
      port: 8040
      targetPort: 80
    - name: custom
      protocol: TCP
      port: 81
      targetPort: 81
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-fpm-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-fpm
  template:
    metadata:
      labels:
        app: php-fpm
    spec:
      containers:
      - name: php-fpm
        image: libraryapi-php-fpm:latest
        ports:
        - containerPort: 9000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"

---

apiVersion: v1
kind: Service
metadata:
  name: php-fpm-service
spec:
  selector:
    app: php-fpm
  ports:
    - name: php
      protocol: TCP
      port: 9000
      targetPort: 9000
  type: NodePort
